# Generated by Django 6.0.3 on 2026-03-21 23:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('par', models.CharField(max_length=10)),
                ('tipo', models.CharField(choices=[('acima', 'Acima de'), ('abaixo', 'Abaixo de')], max_length=6)),
                ('valor_referencia', models.DecimalField(decimal_places=4, max_digits=12)),
                ('ativo', models.BooleanField(default=True)),
                ('disparado', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('disparado_em', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alerta',
                'verbose_name_plural': 'Alertas',
            },
        ),
        migrations.CreateModel(
            name='HistoricoCotacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('par', models.CharField(max_length=10)),
                ('valor_compra', models.DecimalField(decimal_places=4, max_digits=12)),
                ('valor_venda', models.DecimalField(decimal_places=4, max_digits=12)),
                ('variacao', models.DecimalField(decimal_places=2, max_digits=6)),
                ('consultado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Histórico de Cotação',
                'verbose_name_plural': 'Histórico de Cotações',
                'ordering': ['-consultado_em'],
            },
        ),
        migrations.CreateModel(
            name='MoedaFavorita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('par', models.CharField(max_length=10)),
                ('apelido', models.CharField(blank=True, max_length=50)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moedas_favoritas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Moeda Favorita',
                'verbose_name_plural': 'Moedas Favoritas',
                'unique_together': {('usuario', 'par')},
            },
        ),
    ]
